"""
Django settings for TeachingPlatformCRM project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ece_x5yx=dmsq9%$8!_#i+=j*tey07w_7!7u6*gn^g)6n5g!bj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
    'rbac.apps.RbacConfig',
    'stark.apps.StarkConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rbac.middleware.rbac.RbacMiddleware',
]

ROOT_URLCONF = 'TeachingPlatformCRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TeachingPlatformCRM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 这里是固定的
        'NAME': 'crm',  # 将要连接的数据库名
        'USER': 'root',  # 数据库用户名
        'HOST': '127.0.0.1',  # 连接的地址(默认本机)
        'PORT': 3306  # 端口号
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "statics"),
]

AUTH_USER_MODEL = "web.Staff"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"

LOGIN_URL = "/login/"
# --------------------------------------邮件功能相关配置信息------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.163.com'  # 发送邮件的邮箱的SMTP服务器

EMAIL_PORT = 25  # 发件箱的SMTP服务器端口

EMAIL_HOST_USER = "lw18932335520@163.com"  # 发送邮件的邮箱地址

EMAIL_HOST_PASSWORD = "liuwei123"  # 发送邮件的邮箱密码(这里使用的是授权码)

# ------------------------------------------权限相关配置信息------------------------------------------------------------

PERMISSION_SESSION_KEY = "permission_url_list"  # session中保存权限URL列表的key

MENU_SESSION_KEY = "permission_menu_list"  # session中保存菜单列表的key

VAILD_URL_LIST = [                       # 这是一个权限URL白名单（正则）
    "/login/",
    "/admin/.*",
]

EXCLUDE_URL = [                         # 批量获取项目URL时需要提出的部分
    "/admin/.*",
    "/login/",
    "/logout/",
    "/index/",
]

NO_PERMISSION_LIST = [                  # 需要登录但是不需要权限的URL
    "/logout/",
    "/index/",
]
# ----------------------------------------------业务中的用户表----------------------------------------------------------
RBAC_USER_MODEL_CLASS = "web.models.Staff"

