from django.utils.safestring import mark_safe
"""
支持    http://fontawesome.dashgame.com/  网站的图标
"""


icon_list = [
    ['fa-snowflake-o', mark_safe('<i class="fa fa-snowflake-o" aria-hidden="true"></i>')],
    ['fa-free-code-camp', mark_safe('<i class="fa fa-free-code-camp" aria-hidden="true"></i>')],
    ['fa-envelope-open-o', mark_safe('<i class="fa fa-envelope-open-o" aria-hidden="true"></i>')],
    ['fa-handshake-o', mark_safe('<i class="fa fa-handshake-o" aria-hidden="true"></i>')],
    ['fa-window-restore', mark_safe('<i class="fa fa-window-restore" aria-hidden="true"></i>')],
    ['fa-wpexplorer', mark_safe('<i class="fa fa-wpexplorer" aria-hidden="true"></i>')],
    ['fa-balance-scale', mark_safe('<i class="fa fa-balance-scale" aria-hidden="true"></i>')],
    ['fa-briefcase', mark_safe('<i class="fa fa-briefcase" aria-hidden="true"></i>')],
    ['fa-cloud-download', mark_safe('<i class="fa fa-cloud-download" aria-hidden="true"></i>')],
    ['fa-credit-card-alt', mark_safe('<i class="fa fa-credit-card-alt" aria-hidden="true"></i>')],
    ['fa-desktop', mark_safe('<i class="fa fa-desktop" aria-hidden="true"></i>')],
    ['fa-home', mark_safe('<i class="fa fa-home" aria-hidden="true"></i>')],
    ['fa-paper-plane-o', mark_safe('<i class="fa fa-paper-plane-o" aria-hidden="true"></i>')],
    ['fa-puzzle-piece', mark_safe('<i class="fa fa-puzzle-piece" aria-hidden="true"></i>')],
    ['fa-recycle', mark_safe('<i class="fa fa-recycle" aria-hidden="true"></i>')],
    ['fa-bank', mark_safe('<i class="fa fa-bank" aria-hidden="true"></i>')],
    ['fa-address-card-o', mark_safe('<i class="fa fa-address-card-o" aria-hidden="true"></i>')],
    ['fa-thermometer-three-quarters',
     mark_safe('<i class="fa fa-thermometer-three-quarters" aria-hidden="true"></i>')],
    ['fa-calculator', mark_safe('<i class="fa fa-calculator" aria-hidden="true"></i>')],
    ['fa-bullseye', mark_safe('<i class="fa fa-bullseye" aria-hidden="true"></i>')],
    ['fa-bug', mark_safe('<i class="fa fa-bug" aria-hidden="true"></i>')],
    ['fa-bookmark-o', mark_safe('<i class="fa fa-bookmark-o" aria-hidden="true"></i>')],
    ['fa-cube', mark_safe('<i class="fa fa-cube" aria-hidden="true"></i>')],
    ['fa-calendar-check-o', mark_safe('<i class="fa fa-calendar-check-o" aria-hidden="true"></i>')],
    ['fa-cubes', mark_safe('<i class="fa fa-cubes" aria-hidden="true"></i>')],
    ['fa-bell-slash-o', mark_safe('<i class="fa fa-bell-slash-o" aria-hidden="true"></i>')],
    ['fa-caret-square-o-down',
     mark_safe('<i class="fa fa-caret-square-o-down" aria-hidden="true"></i>')],
    ['fa-cart-arrow-down', mark_safe('<i class="fa fa-cart-arrow-down" aria-hidden="true"></i>')],
    ['fa-check-square-o', mark_safe('<i class="fa fa-check-square-o" aria-hidden="true"></i>')],
    ['fa-circle-o-notch', mark_safe('<i class="fa fa-circle-o-notch" aria-hidden="true"></i>')],
    ['fa-cloud', mark_safe('<i class="fa fa-cloud" aria-hidden="true"></i>')],
    ['fa-code-fork', mark_safe('<i class="fa fa-code-fork" aria-hidden="true"></i>')],
    ['fa-comment', mark_safe('<i class="fa fa-comment" aria-hidden="true"></i>')],
    ['fa-comments', mark_safe('<i class="fa fa-comments" aria-hidden="true"></i>')],
    ['fa-creative-commons', mark_safe('<i class="fa fa-creative-commons" aria-hidden="true"></i>')],
    ['fa-dashboard', mark_safe('<i class="fa fa-dashboard" aria-hidden="true"></i>')],
    ['fa-cutlery', mark_safe('<i class="fa fa-cutlery" aria-hidden="true"></i>')],
    ['fa-download', mark_safe('<i class="fa fa-download" aria-hidden="true"></i>')],
    ['fa-database', mark_safe('<i class="fa fa-database" aria-hidden="true"></i>')],
    ['fa-diamond', mark_safe('<i class="fa fa-diamond" aria-hidden="true"></i>')],
]
