# Generated by Django 2.1.7 on 2019-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='一级菜单标题')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('url', models.CharField(max_length=128, verbose_name='含正则的url')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
                ('name', models.CharField(default=None, max_length=32, unique=True, verbose_name='URL的别名')),
                ('menu', models.ForeignKey(blank=True, help_text='如果为空则表示不是菜单, 如果有值就为二级菜单', null=True, on_delete=False, to='rbac.Menu', verbose_name='所属的一级菜单')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=False, to='rbac.Permission', verbose_name='用于关联显示的二级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('permission', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='角色所有权限')),
            ],
        ),
    ]
